services:
  doh-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: doh-proxy
    ports: 
      - "3000:3000"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

    dnsdist:
    image: powerdns/dnsdist-19:latest
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    ports:
      - "8085:53/udp"
