services:
  doh-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: doh-proxy
    env_file:
      - .env
    networks:
      - doh-network
    labels:
      - "traefik.enable=true"  # Explicitly enable Traefik for this container
      - "traefik.http.routers.doh-proxy.rule=Host(`${DOH_HOSTNAME}`)"
      - "traefik.http.routers.doh-proxy.tls.certresolver=myresolver"
      - "traefik.http.services.doh-proxy.loadbalancer.server.port=3000"
  dnsdist:
    image: powerdns/dnsdist-19:latest
    container_name: dnsdist
    volumes:
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    networks:
      - doh-network
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"  # Only expose containers with 'traefik.enable=true'
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"  # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"  # Use HTTPS
      - "--certificatesresolvers.myresolver.tailscale=true"
      - "--accesslog=true"
    networks:
      - doh-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock

networks:
  doh-network:
    driver: bridge
